export const CONTROLLER_INFO_REQUEST = 'CONTROLLER_INFO_REQUEST'
export const CONTROLLER_INFO_RESPONSE = 'CONTROLLER_INFO_RESPONSE'

export const SET_BRIGHTNESS_REQUEST = 'SET_BRIGHTNESS_REQUEST'
export const SET_BRIGHTNESS_RESPONSE = 'SET_BRIGHTNESS_RESPONSE'