export const CONTROLLER_INFO_REQUEST = 'CONTROLLER_INFO_REQUEST';
export const CONTROLLER_INFO_RESPONSE = 'CONTROLLER_INFO_RESPONSE';

export const TOGGLE_LIGHT_REQUEST = 'TOGGLE_LIGHT_REQUEST';
export const TOGGLE_LIGHT_RESPONSE = 'TOGGLE_LIGHT_RESPONSE';

export const SET_BRIGHTNESS_REQUEST = 'SET_BRIGHTNESS_REQUEST';
export const SET_BRIGHTNESS_RESPONSE = 'SET_BRIGHTNESS_RESPONSE';

export const SET_HUE_REQUEST = 'SET_HUE_REQUEST';
export const SET_HUE_RESPONSE = 'SET_HUE_RESPONSE';

export const SET_SATURATION_REQUEST = 'SET_SATURATION_REQUEST';
export const SET_SATURATION_RESPONSE = 'SET_SATURATION_RESPONSE';